export default [
  {
    id: 1,
    brand: 'Audi',
    rentPrice: 100,
    colorId: 1,
    info: 'Building upon a progressive line of innovative luxury vehicles.',
  },
  {
    id: 2,
    brand: 'Audi',
    rentPrice: 100,
    colorId: 2,
    info: 'Building upon a progressive line of innovative luxury vehicles.',
  },
  {
    id: 3,
    brand: 'Ferarri',
    rentPrice: 500,
    colorId: 3,
    info: 'Generally seen as a symbol of speed, luxury and wealth',
  },
  {
    id: 4,
    brand: 'Ford',
    rentPrice: 80,
    colorId: 1,
    info: 'Ford Motor Company (commonly known as Ford)...',
  },
  {
    id: 5,
    brand: 'Peugot',
    rentPrice: 50,
    colorId: 1,
    info: 'One of the foremost pioneers on the international automotive front.',
  },
  {
    id: 6,
    brand: 'Ford',
    rentPrice: 150,
    colorId: 1,
    info: 'Ford Motor Company (commonly known as Ford)...',
  },
  {
    id: 7,
    brand: 'Ford',
    rentPrice: 140,
    colorId: 2,
    info: 'Ford Motor Company (commonly known as Ford)...',
  },
  {
    id: 8,
    brand: 'Lada',
    rentPrice: 20,
    colorId: 3,
    info: 'some text',
  },
  {
    id: 9,
    brand: 'Opel',
    rentPrice: 100,
    colorId: 1,
    info: 'Opel is still headquartered in Rüsselsheim am Main.',
  },
  {
    id: 10,
    brand: 'Opel',
    rentPrice: 100,
    colorId: 2,
    info: 'Opel is still headquartered in Rüsselsheim am Main.',
  },
  {
    id: 11,
    brand: 'Mitsubishi',
    rentPrice: 300,
    colorId: 1,
    info: 'The most innovative cars of all time',
  },
];
